server:
  # 启动端口
  port: 7003
  # 路由前缀
  servlet:
    context-path: /order/server
eureka:
  client:
    # eureka放到服务器上启动时使用驼峰命名更改下划线配置,如使用serviceUrl替换掉service-url
    # 否则Connection refused: connect, Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://118.190.162.48:7001/eureka
    # 服务多久从eureka拉取注册信息,默认为30秒,网关应用如果要迅速获取服务注册状态可以修改为5秒
    registry-fetch-interval-seconds: 30

  instance:
    # 修改服务id不包含主机名等无用信息
    instance-id: order-server
    # 鼠标悬浮服务id时显示ip信息
    prefer-ip-address: true
    # 5秒钟发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 10秒不发送就过期
    lease-expiration-duration-in-seconds: 10
    # 由于有context-path属性,所以需要修改健康监控页地址,否则在注册中心点击时不带有context-path路径
    status-page-url: http://localhost:${server.port}/${server.servlet.context-path}/actuator/info

# 在服务注册中心点击已注册的服务名时提示的服务信息
info:
  app.port: 7003
  app.note: order-server
  app.name: order-server-7003
  company.name: www.zhangbao.com